// VARIANT 1: Single regex chain - minimal lines
// Generated by LZFOF v1.0

export function cleanWhitespace(text: string): string {
    return text.replace(/[ \t]+/g, " ").replace(/^\s+|\s+$/gm, "").replace(/\n{3,}/g, "\n\n").trim();
}
