// VARIANT 2: Pre-compiled regex for performance
// Generated by LZFOF v1.0

const SPACES_TABS = /[ \t]+/g;
const LINE_EDGES = /^\s+|\s+$/gm;
const MULTI_NEWLINES = /\n{3,}/g;

export function cleanWhitespace(text: string): string {
    return text
        .replace(SPACES_TABS, " ")
        .replace(LINE_EDGES, "")
        .replace(MULTI_NEWLINES, "\n\n")
        .trim();
}
