// VARIANT 3: Split and rejoin approach - different algorithm
// Generated by LZFOF v1.0

export function cleanWhitespace(text: string): string {
    return text
        .split('\n')
        .map(line => line.replace(/[ \t]+/g, ' ').trim())
        .join('\n')
        .replace(/\n{3,}/g, '\n\n')
        .trim();
}
