// VARIANT 4: Combined regex - fewer operations
// Generated by LZFOF v1.0

export function cleanWhitespace(text: string): string {
    // Combine horizontal whitespace normalization with trimming
    return text
        .replace(/[^\S\n]+/g, ' ')     // All non-newline whitespace to single space
        .replace(/^ | $/gm, '')         // Trim each line
        .replace(/\n\n\n+/g, '\n\n')   // Collapse 3+ newlines to 2
        .trim();
}
