// VARIANT 5: Early return for empty input - defensive
// Generated by LZFOF v1.0

export function cleanWhitespace(text: string): string {
    if (!text || text.length === 0) return '';

    const normalized = text.replace(/[ \t]+/g, ' ');
    const trimmedLines = normalized.replace(/^\s+|\s+$/gm, '');
    const collapsedNewlines = trimmedLines.replace(/\n{3,}/g, '\n\n');

    return collapsedNewlines.trim();
}
