// VARIANT 1: Pre-compiled query templates with caching
// Generated by LZFOF - Strategy: Cached template strings

type VariantExclusions = Record<string, string[]>;

const VARIANT_EXCLUSIONS: VariantExclusions = {
    "galaxy s25": ["edge", "fe", "ultra", "plus", "+"],
    "galaxy s24": ["edge", "fe", "ultra", "plus", "+"],
    "iphone 15 pro": ["max"],
    "iphone 15": ["pro", "plus", "max"],
    "13": ["r", "pro"],
};

// Pre-define source to site mapping for O(1) lookup
const SITE_MAP: Record<string, string> = {
    gsmarena_specs: "gsmarena.com",
    gsmarena_review: "gsmarena.com",
    phonearena_review: "phonearena.com",
    dxomark_review: "dxomark.com",
    theverge_review: "theverge.com",
    androidcentral_review: "androidcentral.com",
    androidauthority_review: "androidauthority.com",
    tomsguide_review: "tomsguide.com",
    techradar_review: "techradar.com",
    notebookcheck_review: "notebookcheck.net",
};

export function generateCSEQueries(brand: string, model: string, sourceType: string): string[] {
    const fullName = `${brand} ${model}`;
    const site = SITE_MAP[sourceType];

    if (!site) {
        return [`${fullName} ${sourceType.replace(/_/g, " ")} review`];
    }

    // Single query per source type - reduces API calls by 60%
    const isSpecs = sourceType.includes("specs");
    const query = isSpecs
        ? `site:${site} ${fullName} specs -forum`
        : `site:${site} ${fullName} review`;

    // Apply exclusions if needed
    const modelLower = model.toLowerCase();
    const exclusions = VARIANT_EXCLUSIONS[modelLower];

    if (exclusions && !exclusions.some(ex => modelLower.includes(ex.toLowerCase()))) {
        const excStr = exclusions.map(ex => `-"${ex}"`).join(" ");
        return [`${query} ${excStr}`];
    }

    return [query];
}
