// VARIANT 2: Minimal allocation approach
// Generated by LZFOF - Strategy: Reduce string allocations

type VariantExclusions = Record<string, string[]>;

const VARIANT_EXCLUSIONS: VariantExclusions = {
    "galaxy s25": ["edge", "fe", "ultra", "plus", "+"],
    "galaxy s24": ["edge", "fe", "ultra", "plus", "+"],
    "iphone 15 pro": ["max"],
    "iphone 15": ["pro", "plus", "max"],
    "13": ["r", "pro"],
};

// Pre-compiled query generators
const QUERY_GENS: Record<string, (b: string, m: string, f: string) => string[]> = {
    gsmarena_specs: (b, m, f) => [`site:gsmarena.com ${f} specs -forum`],
    gsmarena_review: (b, m, f) => [
        `site:gsmarena.com ${f} review -forum`,
    ],
    phonearena_review: (b, m, f) => [`site:phonearena.com ${f} review`],
    dxomark_review: (b, m, f) => [`site:dxomark.com ${b} ${m}`],
    theverge_review: (b, m, f) => [`site:theverge.com ${f} review`],
    androidcentral_review: (b, m, f) => [`site:androidcentral.com ${f} review`],
    androidauthority_review: (b, m, f) => [`site:androidauthority.com ${f} review`],
    tomsguide_review: (b, m, f) => [`site:tomsguide.com ${f} review`],
    techradar_review: (b, m, f) => [`site:techradar.com ${f} review`],
    notebookcheck_review: (b, m, f) => [`site:notebookcheck.net ${f} review`],
};

export function generateCSEQueries(brand: string, model: string, sourceType: string): string[] {
    const fullName = `${brand} ${model}`;
    const gen = QUERY_GENS[sourceType];

    let queries = gen
        ? gen(brand, model, fullName)
        : [`${fullName} ${sourceType.replace(/_/g, " ")} review`];

    // Fast exclusion check
    const modelLower = model.toLowerCase();
    const exclusions = VARIANT_EXCLUSIONS[modelLower];

    if (!exclusions) return queries;
    if (exclusions.some(ex => modelLower.includes(ex.toLowerCase()))) return queries;

    const excStr = exclusions.map(ex => `-intitle:"${ex}" -inurl:${ex}`).join(" ");
    return queries.map(q => `${q} ${excStr}`);
}
