// VARIANT 3: Template literal with Map for O(1) lookup
// Generated by LZFOF - Strategy: Modern Map + template tagged approach

type VariantExclusions = Record<string, string[]>;

const EXCLUSIONS = new Map<string, string[]>([
    ["galaxy s25", ["edge", "fe", "ultra", "plus", "+"]],
    ["galaxy s24", ["edge", "fe", "ultra", "plus", "+"]],
    ["iphone 15 pro", ["max"]],
    ["iphone 15", ["pro", "plus", "max"]],
    ["13", ["r", "pro"]],
]);

const SITES = new Map<string, string>([
    ["gsmarena_specs", "gsmarena.com"],
    ["gsmarena_review", "gsmarena.com"],
    ["phonearena_review", "phonearena.com"],
    ["dxomark_review", "dxomark.com"],
    ["theverge_review", "theverge.com"],
    ["androidcentral_review", "androidcentral.com"],
    ["androidauthority_review", "androidauthority.com"],
    ["tomsguide_review", "tomsguide.com"],
    ["techradar_review", "techradar.com"],
    ["notebookcheck_review", "notebookcheck.net"],
]);

export function generateCSEQueries(brand: string, model: string, sourceType: string): string[] {
    const fullName = `${brand} ${model}`;
    const site = SITES.get(sourceType);

    if (!site) {
        return [`${fullName} ${sourceType.replace(/_/g, " ")} review`];
    }

    const isSpecs = sourceType.endsWith("_specs");
    const baseQuery = isSpecs
        ? `site:${site} ${fullName} specs -forum`
        : `site:${site} ${fullName} review`;

    // Check exclusions
    const modelLower = model.toLowerCase();
    const exclusions = EXCLUSIONS.get(modelLower);

    if (!exclusions) return [baseQuery];

    // Skip if model contains variant
    for (const ex of exclusions) {
        if (modelLower.includes(ex.toLowerCase())) return [baseQuery];
    }

    // Build exclusion string
    const excParts: string[] = [];
    for (const ex of exclusions) {
        excParts.push(`-"${ex}"`);
    }

    return [`${baseQuery} ${excParts.join(" ")}`];
}
