CREATE TABLE "dynamic_phones" (
	"id" serial PRIMARY KEY NOT NULL,
	"phone_id" text NOT NULL,
	"brand" text NOT NULL,
	"model" text NOT NULL,
	"release_date" timestamp,
	"overall_score" integer,
	"category" text,
	"summary" text,
	"pros" text,
	"cons" text,
	"camera_score" numeric(4, 2),
	"battery_score" numeric(4, 2),
	"performance_score" numeric(4, 2),
	"display_score" numeric(4, 2),
	"software_score" numeric(4, 2),
	"design_score" numeric(4, 2),
	"longevity_score" numeric(4, 2),
	"camera_main" text,
	"camera_telephoto" text,
	"camera_video" text,
	"last_processed_at" timestamp NOT NULL,
	"enrichment_status" text NOT NULL,
	"facts_version" text NOT NULL,
	"confidence" integer,
	"processing_time_ms" integer,
	"full_data" jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "dynamic_phones_phone_id_unique" UNIQUE("phone_id")
);
--> statement-breakpoint
CREATE TABLE "processed_phones" (
	"id" serial PRIMARY KEY NOT NULL,
	"phone_id" text NOT NULL,
	"brand" text NOT NULL,
	"model" text NOT NULL,
	"release_date" timestamp,
	"overall_score" integer,
	"category" text,
	"summary" text,
	"pros" text,
	"cons" text,
	"camera_score" numeric(4, 2),
	"battery_score" numeric(4, 2),
	"performance_score" numeric(4, 2),
	"display_score" numeric(4, 2),
	"software_score" numeric(4, 2),
	"design_score" numeric(4, 2),
	"longevity_score" numeric(4, 2),
	"camera_main" text,
	"camera_telephoto" text,
	"camera_video" text,
	"last_processed_at" timestamp NOT NULL,
	"enrichment_status" text NOT NULL,
	"facts_version" text NOT NULL,
	"confidence" integer,
	"processing_time_ms" integer,
	"full_data" jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "processed_phones_phone_id_unique" UNIQUE("phone_id")
);
--> statement-breakpoint
CREATE TABLE "processing_metadata" (
	"id" serial PRIMARY KEY NOT NULL,
	"total_processed_phones" integer DEFAULT 0,
	"last_updated" timestamp NOT NULL,
	"avg_processing_time" integer,
	"total_deepseek_calls" integer,
	"avg_confidence" integer,
	"created_at" timestamp DEFAULT now()
);
