// VARIANT 1: Using fetch instead of axios
// Generated by LZFOF v1.0

interface Logger {
    info: (phase: string, msg: string) => void;
    success: (phase: string, msg: string) => void;
    warn: (phase: string, msg: string) => void;
}

const noopLogger: Logger = { info: () => { }, success: () => { }, warn: () => { } };

export async function requestArchiveSave(
    url: string,
    accessKey: string,
    secretKey: string,
    logger: Logger = noopLogger
): Promise<boolean> {
    if (!accessKey || !secretKey) {
        logger.info('SAVE_API', 'No credentials. Skipping.');
        return false;
    }

    logger.info('SAVE_API', `Requesting save: ${url.slice(0, 60)}...`);

    try {
        const response = await fetch('https://web.archive.org/save/', {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Authorization': `LOW ${accessKey}:${secretKey}`,
                'Content-Type': 'application/x-www-form-urlencoded',
                'User-Agent': 'SmartMatch Discovery Bot/1.0',
            },
            body: `url=${encodeURIComponent(url)}`,
            signal: AbortSignal.timeout(30000),
        });

        if (response.ok) {
            logger.success('SAVE_API', 'Archive save requested successfully');
            return true;
        }

        logger.warn('SAVE_API', `Unexpected status: ${response.status}`);
        return false;
    } catch (e: unknown) {
        logger.warn('SAVE_API', `Save request failed: ${(e as Error).message}`);
        return false;
    }
}
