// VARIANT 2: Compact with early return pattern
// Generated by LZFOF v1.0

interface Logger {
    info: (phase: string, msg: string) => void;
    success: (phase: string, msg: string) => void;
    warn: (phase: string, msg: string) => void;
}

const noopLogger: Logger = { info: () => { }, success: () => { }, warn: () => { } };

export async function requestArchiveSave(
    url: string,
    accessKey: string,
    secretKey: string,
    logger: Logger = noopLogger
): Promise<boolean> {
    if (!accessKey || !secretKey) return (logger.info('SAVE_API', 'No credentials'), false);

    logger.info('SAVE_API', `Requesting save: ${url.slice(0, 60)}...`);

    const ctrl = new AbortController();
    const timeout = setTimeout(() => ctrl.abort(), 30000);

    try {
        const res = await fetch('https://web.archive.org/save/', {
            method: 'POST',
            headers: {
                Accept: 'application/json',
                Authorization: `LOW ${accessKey}:${secretKey}`,
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            body: `url=${encodeURIComponent(url)}`,
            signal: ctrl.signal,
        });

        clearTimeout(timeout);
        return res.ok ? (logger.success('SAVE_API', 'Success'), true) : (logger.warn('SAVE_API', `Status: ${res.status}`), false);
    } catch (e) {
        clearTimeout(timeout);
        return (logger.warn('SAVE_API', `Failed: ${(e as Error).message}`), false);
    }
}
