// VARIANT 1: Direct write without atomic rename
// Generated by LZFOF v1.0

import fs from 'fs/promises';

export async function saveFailureCache(cache: Record<string, unknown>, cachePath: string): Promise<boolean> {
    try {
        await fs.writeFile(cachePath, JSON.stringify(cache, null, 2), 'utf8');
        return true;
    } catch {
        return false;
    }
}
