// VARIANT 2: Sync version with atomic rename
// Generated by LZFOF v1.0

import fs from 'fs';

export function saveFailureCache(cache: Record<string, unknown>, cachePath: string): boolean {
    try {
        const tmp = cachePath + '.tmp';
        fs.writeFileSync(tmp, JSON.stringify(cache, null, 2), 'utf8');
        fs.renameSync(tmp, cachePath);
        return true;
    } catch {
        return false;
    }
}
