// VARIANT 3: Compact JSON without pretty print
// Generated by LZFOF v1.0

import fs from 'fs/promises';

export async function saveFailureCache(cache: Record<string, unknown>, cachePath: string): Promise<boolean> {
    try {
        const tmp = cachePath + '.tmp';
        await fs.writeFile(tmp, JSON.stringify(cache), 'utf8');
        await fs.rename(tmp, cachePath);
        return true;
    } catch {
        return false;
    }
}
