// VARIANT 1: Simplified with spread operator
// Generated by LZFOF v1.0

interface FailureCacheEntry {
    retryCount: number;
    nextRetry: string;
    doNotRetry?: boolean;
    failureReason?: string;
}
type FailureCache = Record<string, FailureCacheEntry>;

const BACKOFF_HOURS = [1, 4, 12, 24];

export function cacheArchiveFailure(
    cacheInput: FailureCache,
    url: string,
    doNotRetry = false,
    failureReason?: string | null,
    now?: string | Date | null
): FailureCacheEntry {
    const cache = JSON.parse(JSON.stringify(cacheInput)) as FailureCache;
    const timestamp = now ? (typeof now === 'string' ? new Date(now) : now) : new Date();
    const existing = cache[url];
    const retryCount = (existing?.retryCount ?? 0) + 1;
    const backoffHours = BACKOFF_HOURS[Math.min(retryCount - 1, 3)] ?? 24;

    return {
        retryCount,
        nextRetry: new Date(timestamp.getTime() + backoffHours * 3600000).toISOString(),
        ...(doNotRetry && { doNotRetry }),
        ...(failureReason && { failureReason }),
        ...(!failureReason && existing?.failureReason && { failureReason: existing.failureReason }),
    };
}
