// VARIANT 2: Pure function approach
// Generated by LZFOF v1.0

interface FailureCacheEntry {
    retryCount: number;
    nextRetry: string;
    doNotRetry?: boolean;
    failureReason?: string;
}
type FailureCache = Record<string, FailureCacheEntry>;

const BACKOFF = [1, 4, 12, 24];

export function cacheArchiveFailure(
    cacheInput: FailureCache,
    url: string,
    doNotRetry = false,
    failureReason?: string | null,
    now?: string | Date | null
): FailureCacheEntry {
    const cache = JSON.parse(JSON.stringify(cacheInput)) as FailureCache;
    const timestamp = now ? (typeof now === 'string' ? new Date(now) : now) : new Date();
    const prev = cache[url];
    const retryCount = (prev?.retryCount ?? 0) + 1;

    const entry: FailureCacheEntry = {
        retryCount,
        nextRetry: new Date(timestamp.getTime() + (BACKOFF[Math.min(retryCount - 1, 3)] ?? 24) * 3600000).toISOString(),
    };

    if (doNotRetry) entry.doNotRetry = true;
    if (failureReason || prev?.failureReason) {
        entry.failureReason = failureReason ?? prev?.failureReason;
    }

    return entry;
}
