// VARIANT 3: Functional with Object.assign
// Generated by LZFOF v1.0

interface FailureCacheEntry {
    retryCount: number;
    nextRetry: string;
    doNotRetry?: boolean;
    failureReason?: string;
}
type FailureCache = Record<string, FailureCacheEntry>;

const BACKOFF = [1, 4, 12, 24];

export function cacheArchiveFailure(
    cacheInput: FailureCache,
    url: string,
    doNotRetry = false,
    failureReason?: string | null,
    now?: string | Date | null
): FailureCacheEntry {
    const cache = JSON.parse(JSON.stringify(cacheInput)) as FailureCache;
    const timestamp = now ? (typeof now === 'string' ? new Date(now) : now) : new Date();
    const prev = cache[url];
    const retryCount = (prev?.retryCount ?? 0) + 1;
    const hours = BACKOFF[Math.min(retryCount - 1, 3)] ?? 24;

    return Object.assign(
        { retryCount, nextRetry: new Date(timestamp.getTime() + hours * 3600000).toISOString() },
        doNotRetry && { doNotRetry: true },
        (failureReason ?? prev?.failureReason) && { failureReason: failureReason ?? prev?.failureReason }
    );
}
